export const floor = Math.floor
export const sqrt = Math.sqrt
export const round = Math.round
export const PI = Math.PI
export const PI2 = PI * 2
export const min = Math.min
export const pow = Math.pow
export const cos = Math.cos
export const sin = Math.sin
